apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-sidecar-datasource-prometheus
  namespace: {{ sidecar.datasources.prometheus.namespace }}
  labels:
     grafana_datasource: grafana-sidecar-datasource-prometheus
data:
  preometheus_datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: {{ sidecar.datasources.prometheus.url }}
      access: proxy
      isDefault: true
